name: Run MPC Client

on:
  workflow_dispatch:

jobs:
  run-mpc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create ceremony directory
        run: mkdir -p ceremony
      
      - name: Run MPC client container
        run: |
          docker pull ghcr.io/unionlabs/union/mpc-client:v1.2
          docker run -v ${{ github.workspace }}/ceremony:/ceremony -w /ceremony -p 4919:4919 --rm ghcr.io/unionlabs/union/mpc-client:v1.2
